### PR TITLE
Allow connections to localhost to fix SSL error on iOS 9

### LINKED ISSUE #35: “An SSL error has occurred” on Xcode 7 beta
I'm not sure “whose” issue this really is but I'll leave this here for posterity. Someone might google this problem and come to this issue.

After trying to run an existing project on Xcode 7 beta on El Capitan Beta 2, I got this error:

> Could not connect to development server. Ensure node server is running <...>
> 
> An SSL error has occurred and a secure connection to the server cannot be made.

screen shot 2015-06-28 at 03 34 17

In the console, I got this:

```
CFNetwork SSLHandshake failed (-9806)
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9806)
```

A post in [this thread](https://forums.developer.apple.com/thread/4017) offered a workaround that I used:
1. Open `Info.plist`
2. Add these lines to it:

``` xml
<key>NSAppTransportSecurity</key>  
<dict>  
<key>NSAllowsArbitraryLoads</key>  
<true/>  
</dict>
```

This is probably a temporary workaround but it was good enough for me.
Please close if this is irrelevant to this repo.

### PR DESCRIPTION
**Pull request by gaearon**
Fixes #35 by using a workaround from https://github.com/swisspol/GCDWebServer/issues/184#issuecomment-118682814

### CODE REVIEW

**Comment by elliottsj** [comment]
Looks good :+1: 

I'll try this out this evening, then will merge & make a release.

@amccloud @mjohnston What do you think?

**Comment by mjohnston** [comment]
Might need to also add an exception for http://facebook.github.io in the BabelES6 example.

**Comment by amccloud** [comment]
:+1:

**Comment by elliottsj** [comment]
Now using https://facebook.github.io in the BabelES6 example: https://github.com/mjohnston/react-native-webpack-server/commit/fea4608200be4e31c0d2f200dfb07568244d1fb5

**Comment by athibaud** [comment]
ps: [docs](https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/) say the only acceptable values for `NSExceptionMinimumTLSVersion` are:
- `TLSv1.0`
- `TLSv1.1`
- `TLSv1.2`

**Pull request merged**
