### PR TITLE
Fix for react native 0.8-rc.2

### PR DESCRIPTION
**Pull request by jeffreywescott**
This should allow things to work for 0.8-rc.2. However, HOT reloading is still _not_ working.

Some kind of socket.io error. Not sure why.

### CODE REVIEW

**Comment by jsierles** [comment]
This works, thanks! I can't get hot reloading working either, though.

**Comment by jeffreywescott** [comment]
Hot reloading _is_ working for me, it turns out. I had to hit CMD-D in the simulator and reload the debugger-ui in Chrome, but it does work.

**Comment by jsierles** [comment]
I've been using the Chrome debugger with no luck - will keep trying!

**Comment by jeffreywescott** [comment]
I can try to find time to make a sample project ... maybe this weekend.

**Comment by jeffreywescott** [comment]
[Here's a skeleton project](https://github.com/jeffreywescott/react-native-webpack-template) that uses react-native-webpack-server, supports hot-reloading, and ES6 syntax via a custom `.babelrc`.

@mjohnston Any chance you could look at this PR and maybe merge it in?

**Comment by mjohnston** [comment]
Ok, I'll merge this in and make a release. Thanks!

**Pull request merged**
