### PR TITLE
Use `ReactPackager.getDependencies()` to get react native externals

### LINKED ISSUE #23: Use ReactPackager to build externals
Currently, the react-native externals are built by crawling the filesystem. This has caused a number of bugs since react-native's module format is filesystem-independent.

A better solution is to ask the ReactPackager for it's dependency graph. See: https://github.com/facebook/react-native/tree/master/packager#reactpackagergetdependenciesoptions-main

### PR DESCRIPTION
**Pull request by elliottsj**
Thanks to https://gist.github.com/pilwon/7a57624ddde9e6a3bd06

Resolves #23

### CODE REVIEW

**Comment by elliottsj** [comment]
Example project using changes from this PR: https://github.com/elliottsj/react-native-webpack-server-example

**Comment by elliottsj** [comment]
Hey @mjohnston, do you have time to take a look at this PR? If not, can you give commit access to another person who can help review issues & pull requests? I'd be happy to help out if you like.

**Comment by mjohnston** [comment]
@elliottsj Thanks for this. Just made a couple style comments. Once those are addressed I'll pull this in.

**Comment by amccloud** [comment]
@elliottsj please take a look at my PR on your work before you merge this in https://github.com/elliottsj/react-native-webpack-server/pull/1

**Comment by elliottsj** [comment]
@mjohnston Fixed style issues. Also changed from

``` js
var externals = {}
dependencies.forEach(function(dependency) {
  externals[dependency.id] = 'commonjs ' + dependency.id
})
return externals;
```

to

``` js
return dependencies.reduce(function(externals, dependency) {
  externals[dependency.id] = 'commonjs ' + dependency.id;
  return externals;
}, {});
```

to match style from @amccloud's changes in https://github.com/elliottsj/react-native-webpack-server/pull/1.

**Comment by amccloud** [comment]
@mjohnston How do you want to handle backwards compatibility since react-native is moving so fast? This PR is already broken in 0.11.0. Would it make sense to have react-native-webpack-server versions align with react-native?

**Comment by mjohnston** [comment]
@amccloud What exactly is broken in 0.11.0? I suppose it would make sense to align versions with react-native, just curious what is breaking now.

**Comment by amccloud** [comment]
@mjohnston the module object is no longer a plain object. https://github.com/facebook/react-native/commit/bc28a35bda0e358a8296a7b53eb7315b736c6e4b
- `isPolyfill` is now a function
- `id` is now retrieved asynchronously with `getName`

This is the code i'm using now with 0.11.0 https://github.com/amccloud/react-native-webpack-server/commit/3e499dcecd7f57e6b5cf284d24138d065041448f

**Comment by mjohnston** [comment]
Got it. Now that I think about it, I'm not sure if the best path forward is keeping the version numbers aligned 1-to-1. I imagine that most new versions of react-native will require no changes in react-native-webpack-server, especially now that we are pulling the RN dependency tree through the Packager API.

I'm fine with the latest version of react-native-webpack-server only being compatible with the latest version of react-native though.

That being said, I don't really have the bandwidth these days to stay on top of new react-native releases.

@amccloud @elliottsj I'd be happy to give you push access if you're up for it. Let me know and I'll add you as collaborators.

**Comment by amccloud** [comment]
@mjohnston sounds good to me.

@elliottsj Do you want to add my changes to your branch before this merges? We could also just merge this for a `0.3.0` release for those on `react-native@0.9.0`.

**Comment by elliottsj** [comment]
@mjohnston Sounds good to me too.

@amccloud Let's do a 0.3.0 release, then merge in your changes.

**Comment by mjohnston** [comment]
Awesome - both of you should have write access now. Thanks!

**Comment by mjohnston** [comment]
Also added you both as owners for the npm package - you should be able to make releases now.

**Comment by elliottsj** [comment]
Awesome! Any other concerns about this PR? If not, I'll merge and make a 0.3.0 release.

**Comment by mjohnston** [comment]
Nope, looks good.

**Comment by elliottsj** [comment]
Sweet, [0.3.0 is now published](https://www.npmjs.com/package/react-native-webpack-server)

**Comment by mjohnston** [comment]
:zap:

**Comment by niftylettuce** [comment]
@elliottsj @mjohnston I'm still getting this error per https://github.com/t4t5/react-native-router/issues/67#issuecomment-152348190

``````
```log
ERROR in ./~/react-native-router/~/react-native/Libraries/react-native/react-native.js
Module build failed: SyntaxError: /Users/nexus/Public/myproject/react-native/node_modules/react-native-router/node_modules/react-native/Libraries/react-native/react-native.js: Line 20: Did you mean "react"?
  18 | //   var ReactNative = {...require('React'), /* additions */}
  19 | //
> 20 | var ReactNative = Object.assign(Object.create(require('React')), {
     |                                                       ^
  21 |   // Components
  22 |   ActivityIndicatorIOS: require('ActivityIndicatorIOS'),
  23 |   DatePickerIOS: require('DatePickerIOS'),
    at File.errorWithNode (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/transformation/file/index.js:489:13)
    at check (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/transformation/transformers/validation/react.js:23:18)
    at NodePath.CallExpression (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/transformation/transformers/validation/react.js:40:7)
    at NodePath.call (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/path/context.js:90:8)
    at TraversalContext.visitMultiple (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/context.js:108:16)
    at TraversalContext.visit (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/context.js:146:19)
    at Function.traverse.node (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/path/context.js:107:26)
    at TraversalContext.visitMultiple (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/context.js:108:16)
    at TraversalContext.visit (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/context.js:146:19)
    at Function.traverse.node (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/path/context.js:107:26)
    at TraversalContext.visitSingle (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/path/context.js:107:26)
``````

```
```

**Pull request merged**
