### PR TITLE
Add multi entry to support RN for Android

### PR DESCRIPTION
**Pull request by jhen0409**
- Default entry -> `['index.ios', 'index.android']`
- So `webpack.config.js` can be written:

``` js
......
  entry: {
    'index.ios': ['./src/main.js'],
    'index.android': ['./src/main.js']
  },
......
```
- bundle command add `--ios` and `--android` flags

### CODE REVIEW

**Comment by jhen0409** [comment]
But Android bundle host:port cannot be set now.

refer: https://github.com/facebook/react-native/pull/2824

**Comment by jhen0409** [comment]
There are two problems:
1. `MainActivity.java`: js bundle host:port cannot be set now.
2. I swapped the 8080 and 8081 port, but Android runtime appear `not been registered` error (iOS no problem), it appears to be `./src/main` not been successfully executed.

**Comment by elliottsj** [comment]
Thanks for the PR. One change I'm considering is to read the array of entry points directly from the webpack config object, then it won't be necessary anymore to pass them as command line args. Not too sure how to solve the `not been registered` error at this point; do you have any ideas? Currently messing with android on the [android branch](https://github.com/mjohnston/react-native-webpack-server/tree/android).

**Comment by jhen0409** [comment]
@elliottsj 
It's great!
I haven't a idea about `Not been registered` error, but I will continue to track. :|

**Pull request closed without merging**
