### PR TITLE
Make `bundle` command work on React Native 0.12

### PR DESCRIPTION
**Pull request by philikon**
Also accept platform to build the bundle for as an optional parameter and pass it on to the RN packager.

### CODE REVIEW

**Comment by ghost** [comment]
+1 on this then please cut a `0.7.0` to allow users to upgrade to react-native `0.12.0`, which was released yesterday. Until the next RNWS release here's [a workaround](https://github.com/jhabdas/react-native-webpack-starter-kit/commit/8fac6447c15e31167f2df9ddf0903e9966121119) a workaround for those looking to upgrade to the new version of React Native.

**Comment by elliottsj** [comment]
Thanks! Can you try out the latest `master`? Will make a release once I confirm everything's working :smile: (except for hot reloading; still working on getting that working for RN 0.12)

**Comment by elliottsj** [comment]
I've just released [0.7.0](https://github.com/mjohnston/react-native-webpack-server/releases/tag/0.7.0); let me know if it works

**Comment by ghost** [comment]
\o/ will do if someone else doesn't get to it first

**Comment by philikon** [comment]
Sadly I didn't quite test this properly and then it got entirely unfixed by a later commit (not your fault, @elliottsj). Anyway, #102 should fix. Can we get a 0.7.1?

**Comment by elliottsj** [comment]
Thanks, released 0.7.1. My bad actually; I think I broke it in e6b6368b5eff125e5106836c350ae0c042f63f9f. I thought I added the `'[platform]'` thing but I forgot to commit it :confused:

**Pull request merged**
